<a href="https://colab.research.google.com/github/Rakib-Hasan25/python_everything/blob/main/numpy_fundamental.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#what is numpy?
NumPy is the fundamental package for scientific computing in python,
it provide numPy array object and various derieved objcts(such as masked array and matrices) .....
operation -> mathematical , logical , shape manipulation , sorting , selecting , I/0 , discrete Fourier transforms ,  basic linear algebra, basic statistical , random simpulation and much more


##Python is consider to be very slow and its list and dictionary also
numpy array was made by c and crete a wrapper for using python , and array became faster  ,,, and capable of doing data science type jobs



##Difference
###-numpy array have a fixed size at creation ... changing the size of an nd array will create a new array and delete the original
###the element in a numpy are all required to be the same data type, and thus will be the same size in memory
###can perform difficult mathmatical operation
### most famous library ( panda, seaborn, etc ) use numpy array






#Creating a numpy array

In [1]:
import numpy as np

a = np.array([1,2,3])
print(a);
print(type(a))

[1 2 3]
<class 'numpy.ndarray'>


In [4]:
#2D and 3D

b = np.array ([[1,2,4],[4,5,6]])
print(b)

print()

c = np.array(
    [
        [
        [1,3],[3,4]
        ],
         [
             [1,2], [2,33]
          ]
        ]
    )

print(c)


# you can create any D

[[1 2 4]
 [4 5 6]]

[[[ 1  3]
  [ 3  4]]

 [[ 1  2]
  [ 2 33]]]


In [5]:
#dtype
np.array([1,2,3],dtype=float)


array([1., 2., 3.])

In [6]:
np.array([1,2,3],dtype=bool)

array([ True,  True,  True])

In [13]:
#np.arange

a =np.arange(1,11)
print(a)

b= np.arange(1,15,2)
print(b)

c =np.arange(10,1,-1)
print(c)

[ 1  2  3  4  5  6  7  8  9 10]
[ 1  3  5  7  9 11 13]
[10  9  8  7  6  5  4  3  2]


In [17]:
#with reshape

np.arange(1,11).reshape(5,2)# it will make 1 to 10 number in 5 row and 2 column shape

# reshape value 5*2 should equal to np.arange(1,11) total number means 5*2==(11-1)


#np.arange(1,10).reshape(5,2) #give error


array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [21]:
#np.ones

a=np.ones((3,4)) # 3 row and 4 column array initialize with ones
print(a)

print()
b= np.ones((2,2),dtype=int)
print(b)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

[[1 1]
 [1 1]]


In [23]:
#np.zeros
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [25]:
#np.random

a = np.random.random((3,4)) # give random number between 3 to 4
print(a)


[[0.49901532 0.24784531 0.11593062 0.41729303]
 [0.81911411 0.2180329  0.05552682 0.40668868]
 [0.15954921 0.15835563 0.57147201 0.34229837]]


In [33]:
#np.linspace

a= np.linspace(-10,10, 10 )   # np.linspace("lower range","upper range", "number of items") and each number is equally distanced
print(a)

print()

b= np.linspace(-10,10,10,dtype=int)
print(b)



[-10.          -7.77777778  -5.55555556  -3.33333333  -1.11111111
   1.11111111   3.33333333   5.55555556   7.77777778  10.        ]

[-10  -8  -6  -4  -2   1   3   5   7  10]


In [35]:
#np.identity
np.identity(3,dtype=int)
# make 3*3 identity matrix

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

#Array attribute

In [41]:
a1=np.arange(10)
print(a1,)
print()
a2=np.arange(12).reshape(3,4)
print(a2,)
print()
a3 = np.arange(8).reshape(2,2,2)
print(a3,)
print()

[0 1 2 3 4 5 6 7 8 9]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]



In [38]:
#ndim
#give dimension of the array
print(a1.ndim)
print(a2.ndim)
print(a3.ndim)


1
2
3


In [42]:
#shape

print(a1.shape)#how many element in every dimension
print(a2.shape)
print(a3.shape)


#in 3D(2,2,2) here first 2 says how many 2D array in this 3D array
# and the 2nd 2 is says how many 1D array in this 2D array
# and the last 2 says , how many item in this 1D array

(10,)
(3, 4)
(2, 2, 2)


In [43]:
#size
# it give any array total number of element

print(a3.size)


8


In [46]:
#itemsize
a1.itemsize


a1=np.arange(10, dtype=np.int32)
#32 bit integar take 4 byte
print(a1.itemsize)
# it give each array element accupy size in memory

4


In [47]:
#dtype
print(a1.dtype)
print(a2.dtype)

int32
int64


#changing Datatype


In [48]:
#astype
#by using it we can change datatype of an exsisting array
#by default int data type  in int64
#now we change it as int32
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

In [49]:
print(a3)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


why we need these , suppose age is given in a list in float data type , but we don't need that , we can change it
### we can optimize memory consumption


#array operations


In [51]:
a1 = np.arange(12).reshape(3,4)
a2= np.arange(12,24).reshape(3,4)


a1



array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [52]:
#scalar operations
#perform arithmatic operations for every element of matrix (+, - ,* , / ,%)
a1*3


array([[ 0,  3,  6,  9],
       [12, 15, 18, 21],
       [24, 27, 30, 33]])

In [53]:
a1+2

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [54]:
a1 ** 2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [58]:
#relational
#any relational operator (>= , <=, == etc)
a1>5
#check every element element is greater than 5 or not
print(a1>5)

[[False False False False]
 [False False  True  True]
 [ True  True  True  True]]


In [59]:
#vector operations
#arithmatic, or any o
a1 + a2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

#array functions


In [62]:
a1= np.random.random((3,3))



# for np.round we create random number  for 0 to 1


array([[155., 150., 132.],
       [175.,  57., 158.],
       [110.,  56., 141.]])

In [63]:
#max/ min/ sum /prod

np.max (a1) # max element from a1

np.prod(a1)# multiplication of all element







4.201135649172e+18

In [66]:
print(a1)
print()
np.max(a1, axis = 0) # we get max from each column ---> row -> axis =0

[[155. 150. 132.]
 [175.  57. 158.]
 [110.  56. 141.]]



array([175., 150., 158.])

In [67]:
print(a1)
print()

np.max(a1, axis = 1) # we get max from each row --> row -> axis=1

[[155. 150. 132.]
 [175.  57. 158.]
 [110.  56. 141.]]



array([155., 175., 141.])

In [68]:
#mean /median /std /var
np.mean(a1) # mean of whole a1 matrix


126.0

In [69]:
#trigonmetric fuction

np.sin(a1)

array([[-0.87331198, -0.71487643,  0.05308359],
       [-0.8011346 ,  0.43616476,  0.7958241 ],
       [-0.04424268, -0.521551  ,  0.36317137]])

In [70]:
# dot product

# matrix multiplication means dot product


a1 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)
np.dot(a2,a3)

array([[ 906,  960, 1014],
       [1170, 1240, 1310],
       [1434, 1520, 1606]])

In [ ]:
#log and exponents

np.exp(a1)

np.log(a1)

In [72]:
#round / floor / ceil
a1 = np.random.random((3,3))*100
print(a1)
np.round(a1)
# round to nearest integare


[[46.84100112 69.05120322 29.14339749]
 [20.91590559 28.95410133 40.262879  ]
 [37.92832262 80.75408307 37.84718191]]


array([[47., 69., 29.],
       [21., 29., 40.],
       [38., 81., 38.]])

In [ ]:
np.floor (a1)  # floor value
np.ceil(a1)

#indexing and slicing

In [76]:
a1=np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3= np.arange(8).reshape(2,2,2)
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [77]:
#postiive indexing
a1[0]
#negative indexing
a1[-1]

0

In [78]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [79]:
a2[1,2]  # a2[row,col]

6

In [80]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [82]:
# we have to get 3
a3[0,1,1]


#first index means which 2d matrix where it is 0'th
# 2nd index means which which 1D matrix where it is 1'th
# 3rd index means which element here it is 1 th


3

In [83]:
#slicing
print(a1)

a1[2:5]


#every same as list

[0 1 2 3 4 5 6 7 8 9]


array([2, 3, 4])

In [90]:
print(a2)


print()
#suppose i want 0th row
print(a2[0,:])

print()

#suppose i want 0 th row 1th colum to 2th column

print(a2[0,1:3])

print()


#suppose i want 1 th column , oth row to 1 th row


print(a2[   0:2  ,  1 ])

print()


# [[5 6], [9 ,10]] we want to extract this portion


print(a2[  1:  , 1:3])


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[0 1 2 3]

[1 2]

[1 5]

[[ 5  6]
 [ 9 10]]


In [91]:
# for row and we want alternate value


print(a2[ : : 2 , : : 2]) # these 2 means skipping 1 value

[[ 0  2]
 [ 8 10]]


In [101]:
# for 3 D arrray


a3 = np.arange(27).reshape(3,3,3)

print(a3)

print()

print("2nd 2D matrix")

print(a3[1])

print()

print(a3[1,0:2,1:])



print()
print(a3[::2, ::2, :: 2 ])


[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]

2nd 2D matrix
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]

[[10 11]
 [13 14]]

[[[ 0  2]
  [ 6  8]]

 [[18 20]
  [24 26]]]


#Iterating

In [102]:
print(a1)

for i in a1:
  print (i,end=" ")

[0 1 2 3 4 5 6 7 8 9]
0 1 2 3 4 5 6 7 8 9 

In [105]:
print(a2)

for i in a2:
  for j in i:
    print(j, end = " ")
  print()

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
0 1 2 3 
4 5 6 7 
8 9 10 11 


In [107]:
# most important to access any dimentional array every element
for i in np.nditer(a3):
  print(i, end = " ")

0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 

#Reshaping

In [109]:
#transpose
print(a2)
# np.transpose(a2)

# another way

a2.T

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [111]:
# ravel
# convert any dimentional array to 1D array
print(a2)

a2.ravel()


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

#stacking


In [116]:
# horizontal
a1 = np.arange(4).reshape(2,2)
a2 = np.arange(6,10).reshape(2,2)

print(a1)
print()


print(a2)
print()

print("horizonal")
print(np.hstack((a1,a2)))


print(" vertical")



# vertical

np.vstack((a1,a2))




[[0 1]
 [2 3]]

[[6 7]
 [8 9]]

horizonal
[[0 1 6 7]
 [2 3 8 9]]
 vertical


array([[0, 1],
       [2, 3],
       [6, 7],
       [8, 9]])

#spliting

In [117]:
#horizonal split
np.hsplit(a2,2)  # hspit(which matrix, how many partition)

[array([[6],
        [8]]),
 array([[7],
        [9]])]

In [118]:
# vertical split

np.vsplit(a2,2)

[array([[6, 7]]), array([[8, 9]])]